name: stephan.lowe
description: intranet
version: 0.0.1
author: bmjhrn7l.j6vwigfu@rnbymdfv.com
language: scala
buildSystem: ''
buildSystemDetails:
  artefactID: stephanlowe
  parentArtefactID: ''
  buildSystem: maven
  author: null
  createdAt: '2024-11-22 20:22:38'
pipelines:
  pipelines/Marhta_HuelDidi_ReelydoitBrigida_Zulauf:
    name: Marhta_HuelDidi_ReelydoitBrigida_Zulauf
    description: null
    author: bmjhrn7l.j6vwigfu@rnbymdfv.com
    mode: batch
    artefactID: ''
    language: scala
    createdAt: '2024-11-22 20:22:38'
    datasets:
      inputs: []
      outputs: []
    subgraphs: []
    dependencies: {}
datasets: {}
templates: {}
jobs: {}
gemContainer:
  languageVersion: 2.12.15
  gemLibsVersion: 1.1.26
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2024-11-22 20:22:38'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
  businessRules: {}
subgraphs: {}
sqlModels: {}
sqlSnapshots: {}
sqlTests: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies:
- modifiedAt: '2024-11-22T20:22:38.462681Z'
  name: plibMaven
  version: 8.6.0-SNAPSHOT
  id: '809558992'
  createdAt: '2024-11-22T20:22:38.462681Z'
  type: plibMaven
projectDependencies: {}
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
